// Code generated by entc, DO NOT EDIT.

package card

const (
	// Label holds the string label denoting the card type in the database.
	Label = "card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// Table holds the table name of the card in the database.
	Table = "cards"
)

// Columns holds all SQL columns for card fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldName,
}
