// Code generated by entc, DO NOT EDIT.

package card

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/peanut-cc/ent_orm_notes/schema_notes/ent/predicate"
	"github.com/peanut-cc/ent_orm_notes/schema_notes/ent/schema"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v schema.Amount) predicate.Card {
	vc := float64(v)
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAmount), vc))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), vc))
	})
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v schema.Amount) predicate.Card {
	vc := float64(v)
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAmount), vc))
	})
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v schema.Amount) predicate.Card {
	vc := float64(v)
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAmount), vc))
	})
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...schema.Amount) predicate.Card {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Card(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAmount), v...))
	})
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...schema.Amount) predicate.Card {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Card(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAmount), v...))
	})
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v schema.Amount) predicate.Card {
	vc := float64(v)
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAmount), vc))
	})
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v schema.Amount) predicate.Card {
	vc := float64(v)
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAmount), vc))
	})
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v schema.Amount) predicate.Card {
	vc := float64(v)
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAmount), vc))
	})
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v schema.Amount) predicate.Card {
	vc := float64(v)
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAmount), vc))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), vc))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), vc))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...sql.NullString) predicate.Card {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i].String
	}
	return predicate.Card(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...sql.NullString) predicate.Card {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i].String
	}
	return predicate.Card(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), vc))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), vc))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), vc))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), vc))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), vc))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), vc))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), vc))
	})
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldName)))
	})
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldName)))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), vc))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v sql.NullString) predicate.Card {
	vc := v.String
	return predicate.Card(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), vc))
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Card) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		p(s.Not())
	})
}
