// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequiredName holds the string denoting the required_name field in the database.
	FieldRequiredName = "required_name"
	// FieldOptionalName holds the string denoting the optional_name field in the database.
	FieldOptionalName = "optional_name"
	// FieldNilableName holds the string denoting the nilable_name field in the database.
	FieldNilableName = "nilable_name"
	// FieldNilableName2 holds the string denoting the nilable_name2 field in the database.
	FieldNilableName2 = "nilable_name2"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldAge2 holds the string denoting the age2 field in the database.
	FieldAge2 = "age2"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldRequiredName,
	FieldOptionalName,
	FieldNilableName,
	FieldNilableName2,
	FieldAge,
	FieldAge2,
}
