// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Street is the predicate function for street builders.
type Street func(*sql.Selector)
