// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/peanut-cc/ent_orm_notes/quick_use_example/ent/runtime.go

const (
	Version = "v0.4.0" // Version of ent codegen.
)
