// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldField1 holds the string denoting the field1 field in the database.
	FieldField1 = "field1"
	// FieldField2 holds the string denoting the field2 field in the database.
	FieldField2 = "field2"
	// FieldField3 holds the string denoting the field3 field in the database.
	FieldField3 = "field3"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldField1,
	FieldField2,
	FieldField3,
	FieldFirstName,
	FieldLastName,
}
